import { dehydrate, QueryClient } from "@tanstack/react-query";
import Head from "next/head";
import { useProduct } from "../hooks/useProduct";
import { getProducts } from "../services/query/product.query";
import {
  ProductAction,
  ProductModal,
  ProductTable,
} from "../components/pages/product";
import { useState } from "react";

export default function Products() {
  const { products, isLoading } = useProduct();
  const [modal, setModal] = useState({
    open: false,
    type: "",
  });

  const bookHandler = () => {
    setModal({
      open: true,
      type: "book",
    });
  };
  const returnHandler = () => {};

  const closeModal = () => {
    setModal({
      open: false,
      type: "",
    });
  };

  return (
    <div>
      <Head>
        <title>Products|RMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductAction bookHandler={bookHandler} returnHandler={returnHandler} />
      <ProductTable isLoading={isLoading} data={products} />
      <ProductModal modal={modal} closeModal={closeModal} />
    </div>
  );
}

export const getServerSideProps = async () => {
  const queryClient = new QueryClient();

  await getProducts(queryClient);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};
