import { dehydrate, QueryClient } from "@tanstack/react-query";
import { Table } from "antd";
import Head from "next/head";
import { useProduct } from "../hooks/useProduct";
import { getProducts } from "../services/query/product.query";

export default function Products() {
  const{data} = useProduct()
  console.log(data)
  const columns = [
    {
      title: "Name",
      dataIndex: "name",
      key: "name",
    },
    {
      title: "Age",
      dataIndex: "age",
      key: "age",
    },
    {
      title: "Address",
      dataIndex: "address",
      key: "address",
    },
  ];
  return (
    <div>
      <Head>
        <title>Products|RMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Table columns={columns} dataSource={[]} />
    </div>
  );
}

export const getServerSideProps = async () => {
  const queryClient = new QueryClient();

  await getProducts(queryClient);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};
